config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  root 'top#index'
  
  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :conversations do
    resources :messages do
    end
  end

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
    collection do
      post :confirm
    end
  end

  resources :poems, only: [:index, :show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "letteropener"
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = Notification.where(user_id: current_user.id).order(created_at: :desc).where(read: false)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end

  def already_read(boolean)
    if boolean == true
      '既読'
    elsif boolean == false
      '未読'
    end
  end
end

app/views/notifications/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h1>お知らせ</h1>
    <% @notifications.each do |notification| %>
      <div class="row">
        <span><%= already_read(notification.read) %></span>
        <p>
        <%= notification.comment.user.try(:name) %>さんが
        あなたのブログ（<%= link_to "#{notification.comment.blog.title}", blog_path(notification.comment.blog, notification_id: notification.id) %>）にコメントしました。
        </p>
        <p><%= posted_time(notification.created_at) %>前</p>
      </div>
    <% end %>
  </div>
</div>